Time::DATE_FORMATS[:default] = '%b. %e, %Y %H:%M:%S'
Time::DATE_FORMATS[:datetime] = '%b. %e, %Y %H:%M'
Time::DATE_FORMATS[:date] = '%b. %e, %Y'
Time::DATE_FORMATS[:time] = '%H:%M:%S'
Time::DATE_FORMATS[:fulltime] = '%b. %e, %Y %H:%M:%S %z'
Date::DATE_FORMATS[:default] = '%b. %e, %Y'
