#!/usr/bin/env ruby
require 'io/wait'

class RecordGetter
  def initialize
    @records = []
    @trackers = []
  end

  def add_tracker(tracker_type)
    @trackers << RecordTracker.careate(tracker_type)
    return self
  end

  def del_tracker(tracker)
    dt = nil
    @trackers.each{|t|
      if t.class == tracker
        t.stop_track
        dt = t
      end
    }
    @trackers.delete(dt) unless dt == nil
  end

  def get_record
    @trackers.each{|t|
      @records << t.get_record if t.ready?
    }
    oldest_record = @records.sort!.first
    @records[0] = nil
    @records.compact!
    oldest_record
  end

  def ready?
    !@records.empty? || @trackers.any?{|t| t.ready? }
  end
end

class RecordTracker
  def initialize
    @io = exec_cmd
  end

  def get_record
    factory_class.new(@io.gets)
  end

  def ready?
    @io.ready?
  end

  def stop_track
    system "kill -9 #{@io.pid}"
  end

  def self.create(:tracker_type)
    case
    when :file_open
      tracker = FileOpenTracker
    when :focus_change
      tracker = FocusChangeTracker
    else
      raise "Unknown Tracker type"
    end
    return tradker.new
  end
end

class FileOpenTracker < RecordTracker
  def exec_cmd
    IO.popen("sudo ./track_file_open")
  end

  def factory_class
    FileOpenRecord
  end
end

class FocusChangeTracker < RecordTracker
  def exec_cmd
    IO.popen("./track_focus_change")
  end

  def factory_class
    FocusChangeRecord
  end
end

class ActivityRecord
  include Comparable
  attr_reader :time, :record_type, :pid, :pname

  def parse_line(line)
    principle_record = line.split("|")
    principle_record[0] = Time.at(principle_record.first.to_i)
    principle_record
  end

  def <=>(other)
    self.time <=> other.time
  end

  def equal_process?(other)
    self.pid == other.pid && self.pname == other.pname
  end

  def print_record
    puts "#{@time}|#{@record_type}|#{@pid}|#{@pname}"
  end
end

class FileOpenRecord < ActivityRecord
  attr_reader :path

  def initialize(line)
    @time, @record_type, @pid, @pname, @path = parse_line(line)
  end

  def print_record
    puts "#{@time}|#{@record_type}|#{@pid}|#{@pname}|#{@path}"
  end
end

class FocusChangeRecord < ActivityRecord
  def initialize(line)
    @time, @record_type, @pid, @pname = parse_line(line)
  end
end

################################
# main

rg = RecordGetter.new
rg.add_tracker(:file_open).add_tracker(:focus_change)

while 1 do
  if rg.ready?
    record = rg.get_record
    record.print_record
  end
  sleep 1 #sec
end
